# Generated by Django 5.0 on 2024-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Site Information',
                'db_table': 'information',
            },
        ),
    ]
