# Generated by Django 5.0 on 2024-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='streat',
            field=models.CharField(default='11dis', max_length=100),
            preserve_default=False,
        ),
    ]
