# Generated by Django 5.0 on 2024-01-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('name', models.CharField(max_length=60, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=60, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('education', models.TextField(blank=True, max_length=200, null=True)),
                ('github_website', models.URLField(blank=True, null=True)),
                ('linkedin_website', models.URLField(blank=True, null=True)),
                ('facebook_website', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='User Resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
