# Generated by Django 5.0 on 2024-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic', null=True, upload_to='profile_pics/'),
        ),
    ]
