# Generated by Django 5.0 on 2023-12-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_desc_job_job_nature_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
