# Generated by Django 5.0 on 2023-12-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_img',
            field=models.ImageField(default='', upload_to='job_images'),
            preserve_default=False,
        ),
    ]
