# Generated by Django 5.0 on 2024-01-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='job_id',
            new_name='job',
        ),
    ]
